# Generated by Django 2.1.2 on 2018-11-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
