# Generated by Django 2.1.2 on 2018-11-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='des',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
